language: python
python: "3.7"

git:
  depth: 1

branches:
  only:
    - main

os:
  - linux

env:
  - SHARED_LIB=True
  - SHARED_LIB=False

matrix:
  include:
    - os: osx
      language: shell
      env: SHARED_LIB=True
    - os: osx
      language: shell
      env: SHARED_LIB=False
    - os: windows
      language: shell
      before_install:
        - choco install python --version 3.7
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
      env: SHARED_LIB=True

install:
  - pip3 install conan

script:
  - conan create . tanshihaj/stable -o *:shared=$SHARED_LIB --build missing

deploy:
  provider: script
  script: bash tools/deploy_bintray.sh
  on:
    branch: main