git:
  depth: 1

linux: &linux
  os: linux
  language: python
  python: "3.7"

osx: &osx
  os: osx
  language: shell

windows: &windows
  os: windows
  language: shell
  before_install:
    - choco install python --version 3.7
    - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"

matrix:
  include:
    - <<: *linux
      env: SHARED_LIB=True LOCAL_BACKEND=True
    - <<: *linux
      env: SHARED_LIB=False LOCAL_BACKEND=True

    - <<: *osx
      env: SHARED_LIB=True LOCAL_BACKEND=False
    - <<: *osx
      env: SHARED_LIB=False LOCAL_BACKEND=False

    - <<: *osx
      env: SHARED_LIB=True LOCAL_BACKEND=False
    - <<: *osx
      env: SHARED_LIB=False LOCAL_BACKEND=False

    - <<: *windows
      env: SHARED_LIB=True LOCAL_BACKEND=False
    - <<: *windows
      env: SHARED_LIB=False LOCAL_BACKEND=False

install:
  - pip3 install conan

script:
  - conan create . tanshihaj/stable -o *:shared=$SHARED_LIB  -o *:local_backend=$LOCAL_BACKEND -o *:xml_backend=True -o *:network_backend=True --build missing

deploy:
  provider: script
  script: bash tools/deploy_bintray.sh
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^stable/